version: '2'
exclude_patterns:
  - '.circleci/'
  - '.github/'
  - '.storybook/'
  - '.vscode/'
  - 'docs/'
  - 'public/'
  - '**/test/'
  - '**/tests/'
  - '**/__tests/'
  - 'src/**/doc/'
  - 'src/**/story/'
  - 'src/**/stories/'
